project:
  type: website
website:
  title: "Bioconductor Carpentries"
  navbar:
    left:
      - workshops.qmd
      - instructors.qmd
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true