project:
  type: website
website:
  title: "Bioconductor Carpentries"
  navbar:
    left:
      - workshops.qmd
      - instructors.qmd
    right:
      - icon: github
        href: https://github.com/mblue9/bioconductor-carpentries/
        aria-label: GitHub
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true